server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
  server:
    enable-self-preservation: false

spring:
  security:
    user:
      name: admin
      password: admin123

