#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}
#  server:
#    enable-self-preservation: false
#
#spring:
#  security:
#    user:
#      name: admin
#      password: admin123

spring:
  jpa:
    show_sql: false
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  data:
    rest:
      base-path: /api
user-service.host: ${USER_SERVICE_HOST:localhost:8761}
