INSERT INTO ACCOUNT(ID, USERNAME, ACCOUNT_NUMBER, DEFAULT_ACCOUNT, LAST_MODIFIED, CREATED_AT) values (0, 'user', '123456789', TRUE, 12345, 12345);

DELETE FROM USER;
INSERT INTO USER(ID, EMAIL, FIRST_NAME, LAST_NAME, USERNAME, CREATED_AT, LAST_MODIFIED) values (0, 'john.doe@example.com', 'John', 'Doe', 'user', 12345, 12345);
